In [1]:
import csv
import pandas as pd
import numpy as np
from collections import defaultdict

In [2]:
df_CME = pd.read_csv("Input Data/detections_CME.csv", header = None)
M_CME = df_CME.to_numpy()
M_CME[:, 4] = M_CME[:, 4]-1

df_Dino = pd.read_csv("Input Data/detections_Dino.csv")
df_Dino = df_Dino[["timepoint","label_id","x","y","z","intensity","max_intensity"]]
df_Dino = df_Dino.drop("max_intensity", axis=1)
M_Dino = df_Dino.to_numpy()
M_Dino[:, 0] += 1

comp_list = np.zeros((len(M_CME),15), dtype=object)

In [3]:
t_vec = defaultdict(list)
threshold = 5
multi_match_list = []
for vec_Dino in M_Dino:
    t_vec[vec_Dino[0]].append(vec_Dino)

for t_val in t_vec:
    t_vec[t_val] = np.array(t_vec[t_val])

for i, vec_CME in enumerate(M_CME):
    t_val = vec_CME[0]
    dino_group = t_vec[t_val]
    diffs = dino_group[:, 2:5] - vec_CME[2:5]
    dists = np.linalg.norm(diffs, axis=1)
    min_idx = np.argmin(dists)
    min_dist = dists[min_idx]
    best_vec_Dino = dino_group[min_idx]
    comp_list[i, 0:6] = vec_CME
    comp_list[i, 6:12] = best_vec_Dino
    comp_list[i, 12] = min_dist

    # New list by threshold
    below = np.where(dists < threshold)[0]
    if len(below) > 0:
        dino_ids = ",".join(str(int(x)) for x in dino_group[below, 1])
        dists_str = ",".join(f"{dists[j]:.2f}" for j in below)
    else:
        dino_ids = ""
        dists_str = ""
    comp_list[i, 13] = dino_ids
    comp_list[i, 14] = dists_str

multi_match_array = np.array(multi_match_list, dtype=object)

In [4]:
df_comp = pd.DataFrame(comp_list, columns = ["t","ID (CME)", "x (CME)", "y (CME)", 
                                             "z (CME)", "FI (CME)", "t_ig", "ID (Dino)", 
                                             "x (Dino)", "y (Dino)", "z (Dino)", 
                                             "FI (Dino)", "Distance", "Multi ID (Dino)", "Multi Distance (Dino)"])

#df_comp = df_comp.drop("t_ig", axis=1)
df_sorted = df_comp.sort_values(by=["ID (CME)","t"], ascending=[True, True])

In [5]:
df_sorted.to_csv("Output Data/DetectionComparison.csv", index=False)

In [6]:

display(df_comp[df_comp["Distance"]<3.5])

,t,ID (CME),x (CME),y (CME),z (CME),FI (CME),t_ig,ID (Dino),x (Dino),y (Dino),z (Dino),FI (Dino),Distance,Multi ID (Dino),Multi Distance (Dino)
0,1.0,1.0,274.71,525.42,3.6937,97.04,1.0,52.0,274.48068,524.2118,5.474521,325.2,2.164176,52,2.16
1,1.0,2.0,280.94,212.13,7.2465,112.15,1.0,31.0,280.52945,209.67505,4.944871,317.5,3.390107,31,3.39
2,1.0,3.0,331.34,483.79,5.2459,103.52,1.0,39.0,330.5382,482.55966,5.861289,337.8,1.59227,39,1.59
3,1.0,4.0,357.68,331.89,5.159,136.17,1.0,32.0,356.40417,330.43152,4.928988,340.8,1.951361,32,1.95
4,1.0,5.0,256.08,628.71,4.8627,355.77,1.0,53.0,254.15642,628.97144,5.719977,461.8,2.12213,53,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97488,99.0,938.0,543.12,248.77,162.79,39.634,99.0,962.0,540.6431,248.65634,162.2885,238.5,2.529714,962,2.53
97490,99.0,940.0,609.67,382.67,162.69,62.851,99.0,1002.0,607.03326,383.2,162.14659,226.9,2.743828,1002,2.74
97491,99.0,941.0,694.24,50.189,161.96,69.413,99.0,976.0,694.7092,48.823097,161.39287,240.0,1.551604,976,1.55
97492,99.0,942.0,538.48,214.84,162.45,86.382,99.0,980.0,537.5772,213.42221,161.61848,250.2,1.87526,980,1.88
97493,99.0,943.0,562.94,682.91,163.61,187.17,99.0,973.0,562.43835,681.0457,162.00018,311.8,2.51372,973,2.51